### ISSUE TITLE
mode_one 在无独显时运行的问题

### ISSUE THREAD

**Issue by ayuge** [15950552800/Text_select_captcha#2]
1. 在使用 mode_one 版本时报错：AssertionError: Torch not compiled with CUDA enabled

下图是我的 Windows 配置信息：
![image-20200911102113146](https://gitee.com/ayuge/typoraImg/raw/master/typoraImg/20200911102126.png)

我笔记本没有独显，是核显，看代码中已经有了 cpu / gpu 的判断，但是可能是没有改彻底？还是 ... ？

2. 在使用 mode_two 版本时运行 bilbil.py ，我的电脑需要修改 selenium 模拟点击时的 X - 40+ x * lan_x 中 40 改为 22 左右即可正常识别。

**Comment by 15950552800** [comment]
问题1 你是否在stting文件中把GPU置为False？如果为False还报错的话请把报错信息发送给我
问题2 selenium获取元素坐标的时候有偏差，可能在不同分辨率下这个偏差是不同的，我这里只是手工修改了这个偏差

**Comment by ayuge** [comment]
> 
> 
> 问题1 你是否在stting文件中把GPU置为False？如果为False还报错的话请把报错信息发送给我
> 问题2 selenium获取元素坐标的时候有偏差，可能在不同分辨率下这个偏差是不同的，我这里只是手工修改了这个偏差

是的，问题一在修改 setting 文件中 GPU 为 False 后正常识别了；
问题二也确实是因为分辨率的偏差问题导致。
